name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ani2931
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ani2931/fusionpact-backend:latest

      # 5️⃣ Deploy on EC2 via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.205.211.182
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fusionpact-devops-gauntlet
            sudo docker-compose down
            sudo docker pull ani2931/fusionpact-backend:latest
            sudo docker-compose up -d
