name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.ani2931 }}
        password: ${{ secrets.aniruddh2931 }}

    # 4️⃣ Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.aniruddh2931 }}/assignment:latest

    # 5️⃣ Deploy to EC2 via SSH
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/fusionpact-devops-gauntlet
          sudo docker-compose down
          sudo docker pull ${{ secrets.aniruddh2931 }}/assignment:latest
          sudo docker-compose up -d
